ProjetoMVC/Models/ErrorViewModel.cs
namespace ProjetoMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProjetoMVC/Models/Tarefa.cs
namespace ProjetoMVC.Models
{
    public class Tarefa
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public DateTime Prazo { get; set; }

    }
}

ProjetoMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetoMVC.Models;
using System.Diagnostics;

namespace ProjetoMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjetoMVC/Controllers/TarefaController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetoMVC.Data.Repositorio.Interface;
using ProjetoMVC.Models;

namespace ProjetoMVC.Controllers
{
    public class TarefaController : Controller
    {
        private readonly ITarefaRepositorio _tarefaRepositorio;

        public TarefaController(ITarefaRepositorio tarefaRepositorio)
        {
            _tarefaRepositorio = tarefaRepositorio;
        }

        public IActionResult Index()

        {

            var tarefa = _tarefaRepositorio.ListarTarefas();

            return View(tarefa);

        }

        public IActionResult AdicionarTarefa()
        {
            return View();
        }

        public IActionResult InserirTarefa(Tarefa tarefa)
        {
            try
            {

                _tarefaRepositorio.InserirTarefa(tarefa);
            }
            catch (Exception)
            {
                throw;
            }

            return RedirectToAction("Index");

        }

        public IActionResult Editar(int id)

        {

            var tarefa= _tarefaRepositorio.BuscarId(id);

            return View(tarefa);

        }

        public IActionResult EditarTarefa(Tarefa tarefa)
        {
            _tarefaRepositorio.EditarTarefa(tarefa);

            return RedirectToAction("Index");
        }

        public IActionResult Excluir(Tarefa tarefa)

        {

            _tarefaRepositorio.Excluir(tarefa);

            return RedirectToAction("Index");

        }

    }

}

ProjetoMVC/Views/Shared/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h5>Bem vindo!</h5>

ProjetoMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetoMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjetoMVC.styles.css" asp-append-version="true" />
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gerenciador de tarefas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tarefa" asp-action="Index">Tarefas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Lista de tarefas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privac</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProjetoMVC/Views/Tarefa/AdicionarTarefa.cshtml
@model Tarefa
<form asp-controller="Tarefa" asp-action="InserirTarefa" method="post">

    <div class="mb-3" col-md-2>
        <label class="form-label">Titulo</label>
        <input type="text" asp-for="Titulo" class="form-control">
    </div>
    <div class="mb-3">
        <label class="form-label">Descrição</label>
        <input type="text" asp-for="Descricao" class="form-control">
    </div>
    <div class="mb-3">
        <label class="form-label">Prazo</label>
        <input type="date" asp-for="Prazo" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Adicionar</button>
</form>

ProjetoMVC/Views/Tarefa/Editar.cshtml
@model Tarefa
<form asp-controller="Tarefa" asp-action="EditarTarefa" method="post">
    <input type="hidden" asp-for="Id" />

    <div class="mb-3" col-md-2>
        <label class="form-label">Nome</label>
        <input type="text" asp-for="Titulo" class="form-control">
    </div>
    <div class="mb-3" col-md-2>
        <label class="form-label">Descrição</label>
        <input type="text" asp-for="Descricao" class="form-control">
    </div>
    <div class="mb-3" col-md-2>
        <label class="form-label">Prazo</label>
        <input type="date" asp-for="Prazo" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Adicionar</button>
</form>

ProjetoMVC/Views/Tarefa/Index.cshtml
@model List<Tarefa>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Título</th>
            <th scope="col">Descrição</th>
            <th scope="col">Prazo</th>
        </tr>
    </thead>
    <tbody>

        @if (Model != null && Model.Any())

        {

            foreach (Tarefa tarefa in Model)

            {
                <tr>
                    <td>@tarefa.Titulo</td>
                    <td>@tarefa.Descricao </td>
                    <td>@tarefa.Prazo </td>

                    <td>
                        <div class="d-grid gap-2 d-md-block">
                            <a type="submit" class="btn btn-outline-primary" role="button" asp-controller="Tarefa" asp-action="Editar" asp-route-id="@tarefa.Id"><ion-icon name="pencil-outline"></ion-icon></a>
                        </div>
                    </td>
                    <td>
                        <div class="d-grid gap-2 d-md-block">
                            <a type="submit" class="btn btn-outline-danger" role="button" asp-controller="Tarefa" asp-action="Excluir" asp-route-id="@tarefa.Id"><ion-icon name="trash-outline"></ion-icon></a>
                        </div>
                    </td>
                </tr>

            }

        }
    </tbody>
</table>

<div class="text-center">
    <a class="btn btn-outline-primary" type="button" asp-controller="Tarefa" asp-action="AdicionarTarefa">Adicionar tarefa</a>
</div>